### PR TITLE
chore: refactor and cleanup automl tests

### LINKED ISSUE #446: Tests need refactoring
AutoML Create model tests have no teardown. this caused AUTOML_PROJECT_ID project to become the biggest project in the automl (83k LROs, 1.4k models, 540 datasets).

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #446  🦕

list_operation_status failing because it is trying to list 17k LROs.

 I will fix that in a separate PR in some this week by adding some filter or use different project that has low number of LROs

### CODE REVIEW

**Comment by bcoe** [comment]
@munkhuushmgl it looks like a regression in sample tests might have cropped up with this refactor.

**Comment by munkhuushmgl** [comment]
> @munkhuushmgl it looks like a regression in sample tests might have cropped up with this refactor.

I meant to delete those tests (I checked region tags in cloudsite and none of them used anywhere else).

Most of these deleted tests were pointing deleted samples or overlapped with existing tests.

**Review by bcoe — COMMENTED** [review]
Are we basically just getting rid of tests that created a dataset, to ensure that we don't leak resources?

**Comment by munkhuushmgl** [comment]
> Are we basically just getting rid of tests that created a dataset, to ensure that we don't leak resources?

For now, yes. However, we are trying to come up with better ways to test create and delete dataset and models in the futyure.

**Comment by munkhuushmgl** [comment]
@bcoe friendly ping

**Review by bcoe — APPROVED** [review]

**Review by bcoe — APPROVED** [review]

**Pull request merged**
