### PR TITLE
docs: add translate samples

### PR DESCRIPTION
**Pull request by callmehiphop**
Relates to https://github.com/googleapis/nodejs-translate/issues/200

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by callmehiphop** [comment]
Looks like sample tests aren't a thing here? Not sure if I should port them over or not

**Comment by beccasaurus** [comment]
Needs this carried over: https://github.com/googleapis/nodejs-translate/blob/master/samples/test/automlTranslation.test.js

**Comment by callmehiphop** [comment]
@beccasaurus I'm happy to copy the tests over but it doesn't look like they actually get ran?

**Comment by beccasaurus** [comment]
@callmehiphop I'd like to see _"should create a create, list, and delete a dataset"_ moved out of the skipped group to verify API functionality. I get why tests which create a model are currently skipped _(if we let this complete, it can take hours iiuc)_ but would like to see some API functionality tested.

**Comment by beccasaurus** [comment]
#misc #fyi The testing strategy will be changed across all AutoMLs in the coming months ~ using a combination of (1) exec operations and then cancel them (2) interact with pre-created models in CI's GCP project. I have no plans to address this in the near term.

**Comment by callmehiphop** [comment]
@beccasaurus I'm wondering if we should open a new issue for testing samples in automl, I noticed every sample test is currently being skipped, additionally all sample tests are written in the old format.

**Comment by beccasaurus** [comment]
> all sample tests are written in the old format

Is there a reference available for a "new format"?

**Comment by beccasaurus** [comment]
👍 Feel free to an issue against nodejs-automl to address testing strategy across all of the product samples. Again, this is planned but not in the near term. If you pull over the existing test, I'm +1 for this PR

**Comment by callmehiphop** [comment]
@beccasaurus I'm not sure if there any docs on the format differences (@JustinBeckwith ???) but you can look through the translate client. The TL;DR is that old formats bundle multiple examples within a single file and you passed a CLI input to run a specific one. New format puts 1 sample per file and removes the CLI mappings, so we have to update every test to explicitly reference the corresponding file.

**Comment by callmehiphop** [comment]
I think I'll leave the tests skipped for now and address them in #159

**Comment by beccasaurus** [comment]
> removes the CLI mappings

FYI This is optional, samples may have CLIs.

#misc #fyi Most ML API code samples currently offer CLIs and will continue to be CLI executable in the future.

Thanks for #159 

I'll split out the integration test part of it, which is owned by @googleapis/ml-apis

**Pull request merged**
