### PR TITLE
docs(automl_video_intelligence_classification): remove unused samples and files

### PR DESCRIPTION
**Pull request by Strykrol**

### CODE REVIEW

**Review by nnegrey — APPROVED** [review]
LGTM

**Comment by nnegrey** [comment]
FYI: these appear to be used in LOCALIZED docs though.

**Comment by bcoe** [comment]
@nnegrey should we be mindful about removing these samples then? what's the best path forward.

**Comment by nnegrey** [comment]
@Strykrol, what's drift doing about localized stuff?

**Comment by Strykrol** [comment]
So we can hold this PR till those localized docs are updated, if that's the approach you want to take, because we don't really have control on that translation update process atm. 

After talking with the sample clean-up group, we'll consider "Samples still surfaced in localized docs" as out-of-scope for the project. I'll re-check the deletions we were heading towards to make sure they aren't in localized docs.

@nnegrey - I'll shoot you an e-mail about a DRIFT project that will have impact and improvement for translated pages.

**Review by nnegrey — CHANGES_REQUESTED** [review]
Blocking on Localized Pages

**Comment by JustinBeckwith** [comment]
Greetings folks!  This PR is getting moldy.  Is this something we can merge, or should we close it?

**Comment by Strykrol** [comment]
Thanks for the heads-up @JustinBeckwith!

Just rechecked all the deleted samples, and looks like none are surfaced to Localized docs anymore. That unblocks us; this should be fine to merge.

I'll take a look at the conflicts and resolve them tomorrow as needed.

**Comment by bcoe** [comment]
@Strykrol bother you to  rebase with the main branch.

**Review by JustinBeckwith — APPROVED** [review]

**Pull request merged**
